In [18]:
import pandas as pd
import numpy as np

In [48]:
df=pd.read_csv("telco.csv")

In [ ]:
df

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,Female,30,No,No,No,No,0,United States,California,...,0,1639.44,3039.53,5,Stayed,No,45,5306,NaN,NaN
7039,6840-RESVB,Male,38,No,No,Yes,Yes,2,United States,California,...,0,865.20,2807.47,3,Stayed,No,59,2140,NaN,NaN
7040,2234-XADUH,Female,30,No,No,Yes,Yes,2,United States,California,...,0,2135.52,9453.04,4,Stayed,No,71,5560,NaN,NaN
7041,4801-JZAZL,Female,32,No,No,Yes,Yes,2,United States,California,...,0,0.00,319.21,4,Stayed,No,59,2793,NaN,NaN
7042,3186-AJIEK,Male,44,No,No,No,No,0,United States,California,...,0,2043.36,8887.86,4,Stayed,No,38,5097,NaN,NaN

In [ ]:
df["country"].unique()

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 50 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   str
 1   Gender                             7043 non-null   str
 2   Age                                7043 non-null   int64
 3   Under 30                           7043 non-null   str
 4   Senior Citizen                     7043 non-null   str
 5   Married                            7043 non-null   str
 6   Dependents                         7043 non-null   str
 7   Number of Dependents               7043 non-null   int64
 8   Country                            7043 non-null   str
 9   State                              7043 non-null   str
 10  City                               7043 non-null   str
 11  Zip Code                           7043 non-null   int64
 12  Latitude                           7043 non-null   float64
 13  Longitude                          7043 non-null   float64
 14  Population                         7043 non-null   int64
 15  Quarter                            7043 non-null   str
 16  Referred a Friend                  7043 non-null   str
 17  Number of Referrals                7043 non-null   int64
 18  Tenure in Months                   7043 non-null   int64
 19  Offer                              3166 non-null   str
 20  Phone Service                      7043 non-null   str
 21  Avg Monthly Long Distance Charges  7043 non-null   float64
 22  Multiple Lines                     7043 non-null   str
 23  Internet Service                   7043 non-null   str
 24  Internet Type                      5517 non-null   str
 25  Avg Monthly GB Download            7043 non-null   int64
 26  Online Security                    7043 non-null   str
 27  Online Backup                      7043 non-null   str
 28  Device Protection Plan             7043 non-null   str
 29  Premium Tech Support               7043 non-null   str
 30  Streaming TV                       7043 non-null   str
 31  Streaming Movies                   7043 non-null   str
 32  Streaming Music                    7043 non-null   str
 33  Unlimited Data                     7043 non-null   str
 34  Contract                           7043 non-null   str
 35  Paperless Billing                  7043 non-null   str
 36  Payment Method                     7043 non-null   str
 37  Monthly Charge                     7043 non-null   float64
 38  Total Charges                      7043 non-null   float64
 39  Total Refunds                      7043 non-null   float64
 40  Total Extra Data Charges           7043 non-null   int64
 41  Total Long Distance Charges        7043 non-null   float64
 42  Total Revenue                      7043 non-null   float64
 43  Satisfaction Score                 7043 non-null   int64
 44  Customer Status                    7043 non-null   str
 45  Churn Label                        7043 non-null   str
 46  Churn Score                        7043 non-null   int64
 47  CLTV                               7043 non-null   int64
 48  Churn Category                     1869 non-null   str
 49  Churn Reason                       1869 non-null   str
dtypes: float64(8), int64(11), str(31)
memory usage: 3.6 MB

NameError: name 'df' is not defined

:

In [81]:
df["Monthly Charge"].head

<bound method NDFrame.head of 0        39.65
1        80.65
2        95.45
3        98.50
4        76.50
         ...
7038     21.15
7039     84.80
7040    103.20
7041     29.60
7042    105.65
Name: Monthly Charge, Length: 7043, dtype: float64>

In [79]:
df["Offer"].head(10)

0    No Offer
1     Offer E
2     Offer D
3     Offer C
4     Offer C
5     Offer C
6     Offer E
7     Offer B
8     Offer D
9     Offer E
Name: Offer, dtype: str

In [78]:
df["Population"].head(10)

0    68701
1    55668
2    47534
3    27778
4    26265
5    63288
6    21343
7    10558
8    23742
9    32369
Name: Population, dtype: int64

In [57]:
df.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Under 30                                0
Senior Citizen                          0
Married                                 0
Dependents                              0
Number of Dependents                    0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Population                              0
Quarter                                 0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                   0
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download                 0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Satisfaction Score                      0
Customer Status                         0
Churn Label                             0
Churn Score                             0
CLTV                                    0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [52]:
df["Offer"].head(10)

0        NaN
1    Offer E
2    Offer D
3    Offer C
4    Offer C
5    Offer C
6    Offer E
7    Offer B
8    Offer D
9    Offer E
Name: Offer, dtype: str

In [24]:
df["Offer"].unique()

<ArrowStringArray>
[nan, 'Offer E', 'Offer D', 'Offer C', 'Offer B', 'Offer A']
Length: 6, dtype: str

In [25]:
df["Internet Type"].head(10)

0            DSL
1    Fiber Optic
2    Fiber Optic
3    Fiber Optic
4    Fiber Optic
5    Fiber Optic
6    Fiber Optic
7            DSL
8    Fiber Optic
9    Fiber Optic
Name: Internet Type, dtype: str

In [26]:
df["Churn Category"].head(10)

0         Competitor
1         Competitor
2         Competitor
3    Dissatisfaction
4              Price
5         Competitor
6              Other
7    Dissatisfaction
8    Dissatisfaction
9              Price
Name: Churn Category, dtype: str

In [27]:
df["Churn Reason"].head(10)

0                Competitor offered more data
1                Competitor made better offer
2                Competitor made better offer
3                   Limited range of services
4                          Extra data charges
5               Competitor had better devices
6                                  Don't know
7                     Service dissatisfaction
8                   Limited range of services
9    Lack of affordable download/upload speed
Name: Churn Reason, dtype: str

In [56]:
df["Offer"] = df["Offer"].fillna("No Offer",inplace=True)

C:\Users\JOKER\AppData\Local\Temp\ipykernel_7500\87835020.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Offer"] = df["Offer"].fillna("No Offer",inplace=True)

In [42]:
df.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Under 30                                0
Senior Citizen                          0
Married                                 0
Dependents                              0
Number of Dependents                    0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Population                              0
Quarter                                 0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download                 0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Satisfaction Score                      0
Customer Status                         0
Churn Label                             0
Churn Score                             0
CLTV                                    0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [58]:
df["Internet Type"]=df["Internet Type"].fillna("No internet",inplace=True)

C:\Users\JOKER\AppData\Local\Temp\ipykernel_7500\1824262715.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Internet Type"]=df["Internet Type"].fillna("No internet",inplace=True)

In [59]:
df.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Under 30                                0
Senior Citizen                          0
Married                                 0
Dependents                              0
Number of Dependents                    0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Population                              0
Quarter                                 0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                   0
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                           0
Avg Monthly GB Download                 0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Satisfaction Score                      0
Customer Status                         0
Churn Label                             0
Churn Score                             0
CLTV                                    0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [60]:
df["Churn Category"]=df["Churn Category"].fillna("Not Churned", inplace=True)

C:\Users\JOKER\AppData\Local\Temp\ipykernel_7500\1359822551.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Churn Category"]=df["Churn Category"].fillna("Not Churned", inplace=True)

In [47]:
df.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Under 30                                0
Senior Citizen                          0
Married                                 0
Dependents                              0
Number of Dependents                    0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Population                              0
Quarter                                 0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download                 0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Satisfaction Score                      0
Customer Status                         0
Churn Label                             0
Churn Score                             0
CLTV                                    0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [61]:
df["Churn Reason"]=df["Churn Reason"].fillna("Not Churned", inplace=True)

C:\Users\JOKER\AppData\Local\Temp\ipykernel_7500\4190873321.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Churn Reason"]=df["Churn Reason"].fillna("Not Churned", inplace=True)

In [62]:
df.isnull().sum()

Customer ID                          0
Gender                               0
Age                                  0
Under 30                             0
Senior Citizen                       0
Married                              0
Dependents                           0
Number of Dependents                 0
Country                              0
State                                0
City                                 0
Zip Code                             0
Latitude                             0
Longitude                            0
Population                           0
Quarter                              0
Referred a Friend                    0
Number of Referrals                  0
Tenure in Months                     0
Offer                                0
Phone Service                        0
Avg Monthly Long Distance Charges    0
Multiple Lines                       0
Internet Service                     0
Internet Type                        0
Avg Monthly GB Download              0
Online Security                      0
Online Backup                        0
Device Protection Plan               0
Premium Tech Support                 0
Streaming TV                         0
Streaming Movies                     0
Streaming Music                      0
Unlimited Data                       0
Contract                             0
Paperless Billing                    0
Payment Method                       0
Monthly Charge                       0
Total Charges                        0
Total Refunds                        0
Total Extra Data Charges             0
Total Long Distance Charges          0
Total Revenue                        0
Satisfaction Score                   0
Customer Status                      0
Churn Label                          0
Churn Score                          0
CLTV                                 0
Churn Category                       0
Churn Reason                         0
dtype: int64

In [68]:
df.isnull()

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [67]:
sf=df.duplicated().sum()
sf

np.int64(0)

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 50 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   str
 1   Gender                             7043 non-null   str
 2   Age                                7043 non-null   int64
 3   Under 30                           7043 non-null   str
 4   Senior Citizen                     7043 non-null   str
 5   Married                            7043 non-null   str
 6   Dependents                         7043 non-null   str
 7   Number of Dependents               7043 non-null   int64
 8   Country                            7043 non-null   str
 9   State                              7043 non-null   str
 10  City                               7043 non-null   str
 11  Zip Code                           7043 non-null   int64
 12  Latitude                           7043 non-null   float64
 13  Longitude                          7043 non-null   float64
 14  Population                         7043 non-null   int64
 15  Quarter                            7043 non-null   str
 16  Referred a Friend                  7043 non-null   str
 17  Number of Referrals                7043 non-null   int64
 18  Tenure in Months                   7043 non-null   int64
 19  Offer                              7043 non-null   str
 20  Phone Service                      7043 non-null   str
 21  Avg Monthly Long Distance Charges  7043 non-null   float64
 22  Multiple Lines                     7043 non-null   str
 23  Internet Service                   7043 non-null   str
 24  Internet Type                      7043 non-null   str
 25  Avg Monthly GB Download            7043 non-null   int64
 26  Online Security                    7043 non-null   str
 27  Online Backup                      7043 non-null   str
 28  Device Protection Plan             7043 non-null   str
 29  Premium Tech Support               7043 non-null   str
 30  Streaming TV                       7043 non-null   str
 31  Streaming Movies                   7043 non-null   str
 32  Streaming Music                    7043 non-null   str
 33  Unlimited Data                     7043 non-null   str
 34  Contract                           7043 non-null   str
 35  Paperless Billing                  7043 non-null   str
 36  Payment Method                     7043 non-null   str
 37  Monthly Charge                     7043 non-null   float64
 38  Total Charges                      7043 non-null   float64
 39  Total Refunds                      7043 non-null   float64
 40  Total Extra Data Charges           7043 non-null   int64
 41  Total Long Distance Charges        7043 non-null   float64
 42  Total Revenue                      7043 non-null   float64
 43  Satisfaction Score                 7043 non-null   int64
 44  Customer Status                    7043 non-null   str
 45  Churn Label                        7043 non-null   str
 46  Churn Score                        7043 non-null   int64
 47  CLTV                               7043 non-null   int64
 48  Churn Category                     7043 non-null   str
 49  Churn Reason                       7043 non-null   str
dtypes: float64(8), int64(11), str(31)
memory usage: 3.8 MB

In [71]:
df["Payment Method"].unique()

<ArrowStringArray>
['Bank Withdrawal', 'Credit Card', 'Mailed Check']
Length: 3, dtype: str

In [72]:
df["Customer Status"].unique()

<ArrowStringArray>
['Churned', 'Stayed', 'Joined']
Length: 3, dtype: str

In [73]:
df["Zip Code"].head(10)

0    90022
1    90063
2    90065
3    90303
4    90602
5    90660
6    90720
7    91024
8    91106
9    91107
Name: Zip Code, dtype: int64

In [74]:
df.describe()

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Churn Score,CLTV
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,22139.603294,1.951867,32.386767,22.958954,20.515405,64.761692,2280.381264,1.962182,6.860713,749.099262,3034.379056,3.244924,58.505040,4400.295755
std,16.750352,0.962802,1856.767505,2.468929,2.154425,21152.392837,3.001199,24.542061,15.448113,20.418940,30.090047,2266.220462,7.902614,25.104978,846.660055,2865.204542,1.201657,21.170031,1183.057152
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,11.000000,0.000000,1.000000,0.000000,0.000000,18.250000,18.800000,0.000000,0.000000,0.000000,21.360000,1.000000,5.000000,2003.000000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,2344.000000,0.000000,9.000000,9.210000,3.000000,35.500000,400.150000,0.000000,0.000000,70.545000,605.610000,3.000000,40.000000,3469.000000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,17554.000000,0.000000,29.000000,22.890000,17.000000,70.350000,1394.550000,0.000000,0.000000,401.440000,2108.640000,3.000000,61.000000,4527.000000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,36125.000000,3.000000,55.000000,36.395000,27.000000,89.850000,3786.600000,0.000000,0.000000,1191.100000,4801.145000,4.000000,75.500000,5380.500000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,105285.000000,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000,5.000000,96.000000,6500.000000

In [75]:
df["State"].unique()

<ArrowStringArray>
['California']
Length: 1, dtype: str

In [76]:
df.columns

Index(['Customer ID', 'Gender', 'Age', 'Under 30', 'Senior Citizen', 'Married',
       'Dependents', 'Number of Dependents', 'Country', 'State', 'City',
       'Zip Code', 'Latitude', 'Longitude', 'Population', 'Quarter',
       'Referred a Friend', 'Number of Referrals', 'Tenure in Months', 'Offer',
       'Phone Service', 'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Satisfaction Score', 'Customer Status', 'Churn Label',
       'Churn Score', 'CLTV', 'Churn Category', 'Churn Reason'],
      dtype='str')

In [77]:
df.to_csv("telco_cleaned.csv")